In [1156]:
import numpy as np
import pandas as pd

In [1157]:
# data = np.random.randn(1014, 10)

# df = pd.DataFrame(data, columns=['Age', 'BMI', 'Smoking', 'Alcohol', 'Drug_Use', 'Chronic_Hypertension', 
#                                  'Family_History', 'Placenta_Abruption', 'Preterm_Labor', 'Multiple_Gestation'])

# df['BMI'] = np.random.uniform(low=18, high=40, size=1014)

# df['Smoking'] = np.random.choice(['Yes', 'No'], size=1014, p=[0.2, 0.8])

# df['Alcohol'] = np.random.choice(['Yes', 'No'], size=1014, p=[0.1, 0.9])

# df['Drug_Use'] = np.random.choice(['Yes', 'No'], size=1014, p=[0.05, 0.95])

# df['Chronic_Hypertension'] = np.random.choice(['Yes', 'No'], size=1014, p=[0.05, 0.95])

# df['Family_History'] = np.random.choice(['Yes', 'No'], size=1014, p=[0.1, 0.9])

# df['Placenta_Abruption'] = np.random.choice(['Yes', 'No'], size=1014, p=[0.05, 0.95])

# df['Preterm_Labor'] = np.random.choice(['Yes', 'No'], size=1014, p=[0.1, 0.9])

# df['Multiple_Gestation'] = np.random.choice(['Yes', 'No'], size=1014, p=[0.05, 0.95])

# def predict_risk(row):
#     risk = 0
#     if row['Age'] >= 35:
#         risk += 2
#     if row['BMI'] >= 30:
#         risk += 3
#     if row['Smoking'] == 'Yes':
#         risk += 2
#     if row['Alcohol'] == 'Yes':
#         risk += 1
#     if row['Drug_Use'] == 'Yes':
#         risk += 2
#     if row['Chronic_Hypertension'] == 'Yes':
#         risk += 4
#     if row['Family_History'] == 'Yes':
#         risk += 2
#     if row['Placenta_Abruption'] == 'Yes':
#         risk += 3
#     if row['Preterm_Labor'] == 'Yes':
#         risk += 4
#     if row['Multiple_Gestation'] == 'Yes':
#         risk += 2

In [1158]:
df.head()

Age  BMI Chronic_Hypertension Family_History Placenta_Abruption  \
0   25   23                   No             No                 No   
1   35   33                   No            Yes                 No   
2   29   23                   No             No                Yes   
3   30   25                   No             No                 No   
4   35   20                   No             No                 No   

  Preterm_Labor Multiple_Gestation  
0            No                 No  
1            No                 No  
2            No                 No  
3            No                 No  
4            No                 No

In [1159]:
df.describe

<bound method NDFrame.describe of       Age  BMI Chronic_Hypertension Family_History Placenta_Abruption  \
0      25   23                   No             No                 No   
1      35   33                   No            Yes                 No   
2      29   23                   No             No                Yes   
3      30   25                   No             No                 No   
4      35   20                   No             No                 No   
...   ...  ...                  ...            ...                ...   
1009   22   23                   No            Yes                Yes   
1010   55   25                   No             No                 No   
1011   35   25                   No             No                 No   
1012   43   33                   No             No                 No   
1013   32   34                   No             No                 No   

     Preterm_Labor Multiple_Gestation  
0               No                 No  
1        

In [1160]:
data = pd.read_csv('/content/drive/MyDrive/WomenTechies23/Dataset/maternal_health_risk_dataset.csv')

In [1161]:
data.head()

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [1162]:
data.describe

<bound method NDFrame.describe of       Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0      25         130           80  15.0      98.0         86  high risk
1      35         140           90  13.0      98.0         70  high risk
2      29          90           70   8.0     100.0         80  high risk
3      30         140           85   7.0      98.0         70  high risk
4      35         120           60   6.1      98.0         76   low risk
...   ...         ...          ...   ...       ...        ...        ...
1009   22         120           60  15.0      98.0         80  high risk
1010   55         120           90  18.0      98.0         60  high risk
1011   35          85           60  19.0      98.0         86  high risk
1012   43         120           90  18.0      98.0         70  high risk
1013   32         120           65   6.0     101.0         76   mid risk

[1014 rows x 7 columns]>

In [1163]:
# del df['Smoking']
# del df['Alcohol']
# del df['Drug_Use']

In [1164]:
df.head()

Age  BMI Chronic_Hypertension Family_History Placenta_Abruption  \
0   25   23                   No             No                 No   
1   35   33                   No            Yes                 No   
2   29   23                   No             No                Yes   
3   30   25                   No             No                 No   
4   35   20                   No             No                 No   

  Preterm_Labor Multiple_Gestation  
0            No                 No  
1            No                 No  
2            No                 No  
3            No                 No  
4            No                 No

In [1165]:
df['BMI'] = df['BMI'].astype(int)

In [1166]:
age = data[['Age']]

In [1167]:
age.head()

Age
0   25
1   35
2   29
3   30
4   35

In [1168]:
df['Age'] = age

In [1169]:
df.head()

Age  BMI Chronic_Hypertension Family_History Placenta_Abruption  \
0   25   23                   No             No                 No   
1   35   33                   No            Yes                 No   
2   29   23                   No             No                Yes   
3   30   25                   No             No                 No   
4   35   20                   No             No                 No   

  Preterm_Labor Multiple_Gestation  
0            No                 No  
1            No                 No  
2            No                 No  
3            No                 No  
4            No                 No

In [1170]:
df.describe

<bound method NDFrame.describe of       Age  BMI Chronic_Hypertension Family_History Placenta_Abruption  \
0      25   23                   No             No                 No   
1      35   33                   No            Yes                 No   
2      29   23                   No             No                Yes   
3      30   25                   No             No                 No   
4      35   20                   No             No                 No   
...   ...  ...                  ...            ...                ...   
1009   22   23                   No            Yes                Yes   
1010   55   25                   No             No                 No   
1011   35   25                   No             No                 No   
1012   43   33                   No             No                 No   
1013   32   34                   No             No                 No   

     Preterm_Labor Multiple_Gestation  
0               No                 No  
1        

In [1171]:
data.describe

<bound method NDFrame.describe of       Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0      25         130           80  15.0      98.0         86  high risk
1      35         140           90  13.0      98.0         70  high risk
2      29          90           70   8.0     100.0         80  high risk
3      30         140           85   7.0      98.0         70  high risk
4      35         120           60   6.1      98.0         76   low risk
...   ...         ...          ...   ...       ...        ...        ...
1009   22         120           60  15.0      98.0         80  high risk
1010   55         120           90  18.0      98.0         60  high risk
1011   35          85           60  19.0      98.0         86  high risk
1012   43         120           90  18.0      98.0         70  high risk
1013   32         120           65   6.0     101.0         76   mid risk

[1014 rows x 7 columns]>

In [1172]:
df_final = pd.merge(df, data)

In [1173]:
df_final = df_final.drop_duplicates()

In [1174]:
df_final.describe

<bound method NDFrame.describe of        Age  BMI Chronic_Hypertension Family_History Placenta_Abruption  \
0       25   23                   No             No                 No   
1       25   23                   No             No                 No   
2       25   23                   No             No                 No   
3       25   23                   No             No                 No   
4       25   23                   No             No                 No   
...    ...  ...                  ...            ...                ...   
41461   24   25                   No             No                 No   
41464   24   29                   No             No                Yes   
41467   24   33                   No             No                 No   
41470   41   31                   No             No                 No   
41471   46   38                   No             No                 No   

      Preterm_Labor Multiple_Gestation  SystolicBP  DiastolicBP     BS  \
0  

In [1175]:
df_final = df_final.sample(frac = 1)

In [1176]:
df_final.head()

Age  BMI Chronic_Hypertension Family_History Placenta_Abruption  \
6982    30   19                   No             No                 No   
37334   17   27                   No             No                 No   
8328    23   36                   No             No                 No   
14914   42   25                   No             No                 No   
29361   18   23                   No             No                 No   

      Preterm_Labor Multiple_Gestation  SystolicBP  DiastolicBP   BS  \
6982             No                 No         120           80  7.7   
37334            No                 No          90           60  9.0   
8328             No                 No         130           70  6.8   
14914            No                 No          90           60  7.5   
29361           Yes                 No         120           80  6.8   

       BodyTemp  HeartRate RiskLevel  
6982       98.0         70  low risk  
37334     102.0         86  mid risk  
8328       98.0         78  mid risk  
14914      98.0         76  low risk  
29361     102.0         76  low risk

In [1177]:
df_final.describe

<bound method NDFrame.describe of        Age  BMI Chronic_Hypertension Family_History Placenta_Abruption  \
6982    30   19                   No             No                 No   
37334   17   27                   No             No                 No   
8328    23   36                   No             No                 No   
14914   42   25                   No             No                 No   
29361   18   23                   No             No                 No   
...    ...  ...                  ...            ...                ...   
37206   17   33                   No             No                 No   
15922   19   30                   No             No                 No   
20803   48   24                   No             No                 No   
35680   55   21                   No             No                 No   
2528    35   27                   No             No                 No   

      Preterm_Labor Multiple_Gestation  SystolicBP  DiastolicBP    BS  \
6982

In [1178]:
X = pd.get_dummies(df_final, columns=["Chronic_Hypertension", "Family_History", "Placenta_Abruption", "Preterm_Labor", "Multiple_Gestation"], drop_first=True)

In [1179]:
X.head()

Age  BMI  SystolicBP  DiastolicBP   BS  BodyTemp  HeartRate RiskLevel  \
6982    30   19         120           80  7.7      98.0         70  low risk   
37334   17   27          90           60  9.0     102.0         86  mid risk   
8328    23   36         130           70  6.8      98.0         78  mid risk   
14914   42   25          90           60  7.5      98.0         76  low risk   
29361   18   23         120           80  6.8     102.0         76  low risk   

       Chronic_Hypertension_Yes  Family_History_Yes  Placenta_Abruption_Yes  \
6982                          0                   0                       0   
37334                         0                   0                       0   
8328                          0                   0                       0   
14914                         0                   0                       0   
29361                         0                   0                       0   

       Preterm_Labor_Yes  Multiple_Gestation_Yes  
6982                   0                       0  
37334                  0                       0  
8328                   0                       0  
14914                  0                       0  
29361                  1                       0

In [1180]:
del X['HeartRate']

In [1181]:
y = X[['RiskLevel']]

In [1182]:
y['RiskLevel'].replace({"high risk": "2", "mid risk": "1", "low risk" : "0"}, inplace=True)

/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)


In [1183]:
y.head()

RiskLevel
6982          0
37334         1
8328          1
14914         0
29361         0

In [1184]:
del X['RiskLevel']

In [1185]:
X.head()

Age  BMI  SystolicBP  DiastolicBP   BS  BodyTemp  \
6982    30   19         120           80  7.7      98.0   
37334   17   27          90           60  9.0     102.0   
8328    23   36         130           70  6.8      98.0   
14914   42   25          90           60  7.5      98.0   
29361   18   23         120           80  6.8     102.0   

       Chronic_Hypertension_Yes  Family_History_Yes  Placenta_Abruption_Yes  \
6982                          0                   0                       0   
37334                         0                   0                       0   
8328                          0                   0                       0   
14914                         0                   0                       0   
29361                         0                   0                       0   

       Preterm_Labor_Yes  Multiple_Gestation_Yes  
6982                   0                       0  
37334                  0                       0  
8328                   0                       0  
14914                  0                       0  
29361                  1                       0

In [1186]:
X = X.values
y = y.values

In [1187]:
X

array([[ 30.,  19., 120., ...,   0.,   0.,   0.],
       [ 17.,  27.,  90., ...,   0.,   0.,   0.],
       [ 23.,  36., 130., ...,   0.,   0.,   0.],
       ...,
       [ 48.,  24., 120., ...,   0.,   0.,   0.],
       [ 55.,  21., 120., ...,   0.,   0.,   0.],
       [ 35.,  27., 100., ...,   0.,   1.,   0.]])

In [1188]:
y

array([['0'],
       ['1'],
       ['1'],
       ...,
       ['2'],
       ['0'],
       ['0']], dtype=object)

In [1189]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [1190]:
# from sklearn.ensemble import RandomForestClassifier
# classifier = RandomForestClassifier(n_estimators = 50)
# classifier.fit(X_train, y_train)

In [1191]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
from xgboost import XGBClassifier
classifier = XGBClassifier(n_estimators = 50)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=50, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [1192]:
y_train_pred = classifier.predict(X_train)

In [1193]:
y_pred = classifier.predict(X_test)

In [1194]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_train, y_train_pred)
print(cm)
print('Train Accuracy: {}%'.format(round(accuracy_score(y_train, y_train_pred), 4)*100))

[[5197   80   27]
 [ 504 1622   70]
 [  78   39 2178]]
Train Accuracy: 91.85%


In [1195]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_test = le.fit_transform(y_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Test Accuracy: {}%'.format(round(accuracy_score(y_test, y_pred), 4)*100))

[[1258   37   14]
 [ 129  395   27]
 [  28   17  544]]
Test Accuracy: 89.71000000000001%


/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [1196]:
X_train

array([[ 23.,  25.,  90., ...,   0.,   0.,   0.],
       [ 22.,  23., 120., ...,   0.,   0.,   0.],
       [ 55.,  39., 100., ...,   0.,   0.,   0.],
       ...,
       [ 19.,  34., 120., ...,   1.,   0.,   0.],
       [ 32.,  23., 120., ...,   0.,   0.,   0.],
       [ 35.,  26., 120., ...,   0.,   1.,   0.]])

In [1205]:
# import pickle
# pickle.dump(classifier, open('classifier.pkl', 'wb'))